spring:
  application:
    name: gateway-item
logging:
  file:
    path: /log/gateway-item
    name: gateway-item.log
  level:
    root: info
  logback:
    rollingpolicy:
      max-file-size: 10MB
#  main:
#    web-application-type: reactive
#  cloud:
#    nacos:
#      config:
#        server-addr: 1.95.6.188:8848
#        file-extension: yaml
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: user-manager
#          uri:  lb://user-manager
#          predicates:
#            - Path=/user/**
server:
  port: 8080
