server:
  port: 8081
spring:
  application:
    name: user-manager
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  datasource:
    # 数据库连接 URL
    url: jdbc:mysql://localhost:3306/userMange?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    # 数据库用户名
    username: root
    # 数据库密码
    password: yuyuhang66
    # 数据库驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源类型，这里使用 Druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid 数据源配置
    druid:
      # 初始连接池大小
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      # 最大活动连接数
      max-active: 20
      # 获取连接的最大等待时间，单位毫秒
      max-wait: 60000
      # 两个对象空闲时间多久之后进行一次连接有效性检查
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的 SQL，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为 true，不影响性能，并且保证安全性
      test-while-idle: true
      # 应用程序中申请连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 应用程序中归还连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 是否缓存 preparedStatement，提高性能
      pool-prepared-statements: true
      # 最大打开预处理语句数
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat,wall,log4j
      # 通过连接属性配置监控统计信息
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis-plus:
  # Mapper 文件位置
  mapper-locations: classpath*:mapper/*.xml
  # 实体类包路径
  type-aliases-package: com.example.demo.entity
  # 全局配置
  global-config:
    # 数据库配置
    db-config:
      # 逻辑删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
